### ISSUE TITLE
Empty data files

### ISSUE THREAD

**Issue by evhan** [ismartcoding/currency-api#2]
Hello there,

This project seems to have stopped working as of commit 027cf8c6. Every update since then contains just `{"quotes":{}}`.

**Comment by ismartcoding** [comment]
Thank you for providing feedback. I've observed that the upstream API is currently suspended. If anyone knows of a freely available exchange API, kindly share it with us at ismartcoding@gmail.com. I appreciate your assistance, and I will promptly update this repository with the new information.

**Comment by ismartcoding** [comment]
Fixed
