### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by RaptaG** [ismartcoding/currency-api#3]
1. Is the number of currencies fixed (will there ever be more/less)?
2. Which currencies are included?
3. Have you considered using NPM?
4. Should I worry about this API been taken down by GitHub for using Actions too often?

**Comment by ismartcoding** [comment]
1. I am not sure. I think it is enough.
2. All the currencies are include in the result. https://raw.githubusercontent.com/ismartcoding/currency-api/main/latest/data.json
3. Using NPM for what?
4. Yes, you should have a backup.

**Comment by RaptaG** [comment]
3. Host the project on NPM
4. How am I supposed to keep a backup and is there a way to ensure that this does not happen to the repo?

Also, are historical dates ever being deleted after a period of time?
